# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: pquant-conda
channels:
  - bioconda
  - r
dependencies:
  - conda-forge::python=3.8.5
  - r::r-shinydashboard
  - r::r-irkernel
